// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVPI4HbXo2XY5xwoicrhrQUwBLmgwoc8',
    appId: '1:1060207661712:web:bb0183d1963f267aa03e15',
    messagingSenderId: '1060207661712',
    projectId: 'ecommerceapp-abf29',
    authDomain: 'ecommerceapp-abf29.firebaseapp.com',
    storageBucket: 'ecommerceapp-abf29.appspot.com',
    measurementId: 'G-KKXRG8H775',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-4HovCrHBkz5ahNRSxGh3ICWxQkcUT8',
    appId: '1:1060207661712:android:ac647764c3c378aba03e15',
    messagingSenderId: '1060207661712',
    projectId: 'ecommerceapp-abf29',
    storageBucket: 'ecommerceapp-abf29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0pISlxKFTaMTD0jbSN9cDHIWlHAdQaLM',
    appId: '1:1060207661712:ios:eaabcf8776ab23efa03e15',
    messagingSenderId: '1060207661712',
    projectId: 'ecommerceapp-abf29',
    storageBucket: 'ecommerceapp-abf29.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0pISlxKFTaMTD0jbSN9cDHIWlHAdQaLM',
    appId: '1:1060207661712:ios:eaabcf8776ab23efa03e15',
    messagingSenderId: '1060207661712',
    projectId: 'ecommerceapp-abf29',
    storageBucket: 'ecommerceapp-abf29.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVPI4HbXo2XY5xwoicrhrQUwBLmgwoc8',
    appId: '1:1060207661712:web:b8cf260553817db3a03e15',
    messagingSenderId: '1060207661712',
    projectId: 'ecommerceapp-abf29',
    authDomain: 'ecommerceapp-abf29.firebaseapp.com',
    storageBucket: 'ecommerceapp-abf29.appspot.com',
    measurementId: 'G-CTF2N8ZN8V',
  );
}
